### ISSUE TITLE
Stuck at "Loading... Please wait while map loads Thank You"

### ISSUE THREAD

**Issue by emtiazzahid** [KhanShaheb34/nCov19-InteractiveDashboard-BD#10]
**Describe the bug**
Stuck at "Loading... Please wait while map loads Thank You"

**To Reproduce**
1. Go to 'https://www.co-ronabd.info/'
3. Open console

**Screenshots**
![image](https://user-images.githubusercontent.com/10188029/91033022-93235980-e624-11ea-9a3e-a57d85514cfc.png)

**Comment by KhanShaheb34** [comment]
Sorry for the bug. I'm trying to fix it.

**Comment by KhanShaheb34** [comment]
Actually the API this site is using is currently down. I created an issue on the repository of the API. Hope they will fix it soon.

**Comment by KhanShaheb34** [comment]
The API is hosted on a free Heroku tier. And the site went down as it crossed the free tier limit. Now it is up again. And so does [Co-ronaBD.info](https://www.co-ronabd.info/).

If you can, please support the creator of the API from [here](https://github.com/ahmedsadman/covid19-bd). Thank you. 😊
