### ISSUE TITLE
Show count on mouse hover

### ISSUE THREAD

**Issue by ahmedsadman** [KhanShaheb34/nCov19-InteractiveDashboard-BD#2]
**Is your feature request related to a problem? Please describe.**
Areas should be clicked to know the count in that area, this is inconvenient in most cases. A whole different Modal box seems overkill to only show the count.

**Describe the solution you'd like**
Besides the district name, the count should also be shown on mouse hover. Some pretty UI boxes can be designed to improve user experience. Same should work in mobile devices, which is, data should be shown on tap, but the same way as in desktop (not any modal).

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by KhanShaheb34** [comment]
Showing count on mouse hover is a good idea. Thank you.
I'm working on it. 

As hovering isn't possible on mobile devices, I used the modal to show data. And, I'm planning to show some more insight on the modal.

**Comment by KhanShaheb34** [comment]
I added the count with the name on the tooltip box.
Please have a look at the preview [here!](https://ncov19-idbbd.herokuapp.com/)

If you think any more changes should be made, please let me know.
Thank You.
