### ISSUE TITLE
Filter district by searching

### ISSUE THREAD

**Issue by ahmedsadman** [KhanShaheb34/nCov19-InteractiveDashboard-BD#3]
**Is your feature request related to a problem? Please describe.**
Users might need to scroll a long distance (especially on small screens) if they want to look for specific districts

**Describe the solution you'd like**
Create a simple search bar. Using component rendering of React, render only those district that contains the text in the search bar

**Describe alternatives you've considered**
Or, divide the districts by division and make them collapsable on click for easier searching.

**Additional context**
NONE

**Comment by KhanShaheb34** [comment]
Searching through the district list is a good idea. I'm trying to implement this.

Thanks for providing stats in the API. Scrapping was too much heavy task for this small amount of data. :sweat_smile:

**Comment by KhanShaheb34** [comment]
Added a search bar in the district table. :smiley: 
Have a look at the preview from [here](https://ncov19-idbbd.herokuapp.com/).

And please let me know if you find any bug or you want to see any more features.
Thank you. :grin:

**Comment by ahmedsadman** [comment]
Please add a clear icon, which will clear the search text. And also, during the search, the whole _district-data_ section changes it's _vertical positioning_ as the number of rendered district changes (like a jumping effect). It's not an urgent issue, but it's distracting. **To regenerate this: from a desktop screen, type a full district name like "Bogra" or "Rangpur"**. The search bar should keep it's position no matter what you search. Look into that too.
