### ISSUE TITLE
Map goes out of range for accidental zooming/scrolling

### ISSUE THREAD

**Issue by ahmedsadman** [KhanShaheb34/nCov19-InteractiveDashboard-BD#4]
**Describe the bug**
The current map view, if not carefully zoomed out or scrolled, goes out of range. At this point, it's very difficult to relocate the map manually

**To Reproduce**
Steps to reproduce the behaviour:
In either desktop or mobile view, randomly scroll out of range till the map view is totally empty, and then try to relocate the map

**Expected behaviour**
The map should have a fixed boundary. Users can zoom out or scroll the map to a certain level so that it never goes out of range

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KhanShaheb34** [comment]
I did try to fix this once. But I was having some trouble. Then I thought this won't be a trouble for users.

But as it is hampering the user experience, I am going to fix this again.

**Comment by KhanShaheb34** [comment]
Fixed the bug and pushed it to the production build too.
Check it here: https://www.co-ronabd.info/
And please let me know if you find any bug or want any feature.
Thank you! :smiley:
